# Generated by Django 3.1.2 on 2020-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=2, help_text='Latitude of sighting', max_digits=100)),
                ('Longitude', models.DecimalField(decimal_places=2, help_text='Longitude of sighting', max_digits=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique id of squirrel', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift of sighting', max_length=10)),
                ('Date', models.DateField(help_text='Date of this sighting')),
                ('Age', models.CharField(blank=True, help_text='Age of this squirrel', max_length=20)),
                ('Primary_Fur_color', models.CharField(blank=True, max_length=50)),
                ('Location', models.TextField(blank=True)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(blank=True, help_text='whether is likes running or not')),
                ('Chasing', models.BooleanField(blank=True)),
                ('Climbing', models.BooleanField(blank=True)),
                ('Eating', models.BooleanField(blank=True)),
                ('Foraging', models.BooleanField(blank=True)),
                ('Other_Activities', models.TextField(blank=True)),
                ('Kuks', models.BooleanField(blank=True)),
                ('Quaas', models.BooleanField(blank=True)),
                ('Moans', models.BooleanField(blank=True)),
                ('Tail_flags', models.BooleanField(blank=True)),
                ('Tail_twitches', models.BooleanField(blank=True)),
                ('Approaches', models.BooleanField(blank=True)),
                ('Indifferent', models.BooleanField(blank=True)),
                ('Runs_from', models.BooleanField(blank=True)),
            ],
        ),
    ]
